services:
  livreto:
    build: .
    restart: always
    volumes:
      - ./src/files:/app/files 
    env_file:
      - /etc/cisbaf-setup/envs/.env-livreto
    ports:
      - "${LIVRETO_PORT}:8000"  # Certifique-se do uso correto da variável
