# Generated by Django 5.1.2 on 2024-10-09 16:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('livreto', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='livreto',
            name='pages',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
