# Generated by Django 5.1.2 on 2024-10-09 17:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('livreto', '0003_remove_livreto_pages'),
    ]

    operations = [
        migrations.AddField(
            model_name='livreto',
            name='pdf',
            field=models.FileField(default=1, upload_to='livretos/'),
            preserve_default=False,
        ),
    ]
