# Generated by Django 5.1.2 on 2024-10-10 12:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('livreto', '0004_livreto_pdf'),
    ]

    operations = [
        migrations.AddField(
            model_name='livreto',
            name='active',
            field=models.BooleanField(default=True),
        ),
    ]
